name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

jobs:
  test_macos:
    runs-on: macos-13
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: "Run Tests"
      run: "swift test"
        
  test_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: "Run Tests"
      run: "swift test"
